name: Reusable ARM Deployment

on:
  workflow_call:
    inputs:
      templateFile:
        required: true
        type: string
      parametersFile:
        required: true
        type: string
      resourceGroup:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
      PAT:
        required: false   

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout parent repo (BH-Reusable-Templates)
        uses: actions/checkout@v4
        with:
          repository: praveenadmin/BH-Reusable-Templates
          ref: main
          token: ${{ secrets.PAT }} 

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep / ARM
        run: |
          az deployment group create \
            --resource-group "${{ inputs.resourceGroup }}" \
            --template-file "${{ inputs.templateFile }}" \
            --parameters @"${{ inputs.parametersFile }}"